/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            fontFamily: {
                mono: ['"Share Tech Mono"', 'monospace'], // Sci-fi font
                sora: ['"Sora"', 'sans-serif'],
                manrope: ['"Manrope"', 'sans-serif'],
                geist: ['"Geist"', 'monospace'],
            },
            colors: {
                "secondary-fixed": "#89f2ff",
                "primary": "#a8e8ff",
                "inverse-on-surface": "#2f3032",
                "secondary-container": "#03b7c5",
                "surface-container-highest": "#333537",
                "on-background": "#e2e2e4",
                "on-secondary-fixed": "#001f23",
                "primary-fixed": "#b4ebff",
                "on-primary-fixed": "#001f27",
                "on-tertiary-fixed": "#161c21",
                "surface-container-lowest": "#0d0e10",
                "on-secondary-fixed-variant": "#004f56",
                "secondary-fixed-dim": "#4bd9e7",
                "primary-container": "#00d4ff",
                "primary-fixed-dim": "#3cd7ff",
                "on-surface-variant": "#bbc9cf",
                "on-tertiary-container": "#4a5156",
                "on-secondary": "#00363b",
                "surface-tint": "#3cd7ff",
                "inverse-surface": "#e2e2e4",
                "outline-variant": "#3c494e",
                "tertiary-fixed": "#dde3ea",
                "on-primary-fixed-variant": "#004e5f",
                "inverse-primary": "#00677e",
                "on-error": "#690005",
                "secondary": "#4bd9e7",
                "on-secondary-container": "#004248",
                "surface-bright": "#38393b",
                "on-surface": "#e2e2e4",
                "surface-dim": "#121415",
                "on-error-container": "#ffdad6",
                "surface-container-low": "#1a1c1d",
                "surface-container-high": "#282a2c",
                "on-primary": "#003642",
                "error": "#ffb4ab",
                "on-primary-container": "#00586b",
                "on-tertiary": "#2b3136",
                "tertiary-container": "#bdc3ca",
                "on-tertiary-fixed-variant": "#41484d",
                "surface-container": "#1e2022",
                "tertiary": "#d9dfe6",
                "error-container": "#93000a",
                "surface-variant": "#333537",
                "background": "#121415",
                "surface": "#121415",
                "tertiary-fixed-dim": "#c1c7ce",
                "outline": "#859398"
            }
        },
    },
    plugins: [],
}
