"""
brain/core/models.py — Phase 5.1 cognitive value objects

Pure pydantic data models. NO business logic, NO I/O, NO imports from
runtime modules. These are the contracts every later Phase 5 subsystem
(Planner, Skill Manager, Reflection Engine, Evolution Engine) exchanges.

Conventions (mirrors brain/state.py):
  - Frozen models for anything passed across subsystem boundaries.
  - Field(default_factory=...) for mutable containers.
  - ids are opaque strings generated by the caller (uuid4 by default).
"""

from __future__ import annotations

import uuid
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field


def _new_id() -> str:
    """Generate an opaque unique identifier."""
    return uuid.uuid4().hex


class BrainRequest(BaseModel):
    """A single unit of user intent entering the cognitive pipeline."""

    model_config = ConfigDict(frozen=True)

    request_id: str = Field(default_factory=_new_id)
    channel: str = Field(
        default="text",
        description='Origin channel: "text" | "voice_tool" | "rest".',
    )
    text: Optional[str] = Field(
        default=None, description="Raw user text (text/rest channels)."
    )
    tool_call: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Pre-decided tool call (voice_tool channel — Gemini Live "
        "already chose the tool; BrainCore skips planning).",
    )
    sid: Optional[str] = Field(
        default=None, description="Socket.IO session id, if applicable."
    )
    workspace: Optional[str] = Field(
        default=None, description="Target project/workspace name, if known."
    )
    metadata: Dict[str, Any] = Field(default_factory=dict)


class Task(BaseModel):
    """One step of a Plan. Skill binding happens in later milestones."""

    model_config = ConfigDict(frozen=True)

    id: str = Field(default_factory=_new_id)
    intent: str = Field(description="What this task should accomplish.")
    skill_id: Optional[str] = Field(
        default=None, description="Bound skill id (None until Planner exists)."
    )
    params: Dict[str, Any] = Field(default_factory=dict)
    depends_on: List[str] = Field(
        default_factory=list, description="Task ids that must complete first."
    )
    needs_confirmation: bool = Field(
        default=False, description="Requires explicit user approval to run."
    )


class Plan(BaseModel):
    """An ordered/DAG set of Tasks produced by a Planner (Phase 5.2+)."""

    model_config = ConfigDict(frozen=True)

    plan_id: str = Field(default_factory=_new_id)
    tasks: List[Task] = Field(default_factory=list)
    strategy: str = Field(
        default="sequential", description='"sequential" | "dag".'
    )
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    rationale: str = Field(default="")


class BrainContext(BaseModel):
    """
    Everything BrainCore assembled for one request: the request itself plus
    read-only surroundings (memory excerpts, workspace, persona, brain
    snapshot data). Later milestones enrich the payload fields; Phase 5.1
    only defines the shape.
    """

    model_config = ConfigDict(frozen=True)

    request: BrainRequest
    workspace_ctx: Dict[str, Any] = Field(default_factory=dict)
    memories: List[Dict[str, Any]] = Field(default_factory=list)
    persona_state: Dict[str, Any] = Field(default_factory=dict)
    brain_snapshot: Dict[str, Any] = Field(
        default_factory=dict,
        description="Read-only extract of BrainState.snapshot().",
    )
    recent_history: List[Dict[str, Any]] = Field(default_factory=list)


class Reflection(BaseModel):
    """Immutable post-execution evaluation record (produced Phase 5.6+)."""

    model_config = ConfigDict(frozen=True)

    request_id: str
    plan_id: Optional[str] = None
    success: bool = True
    failures: List[Dict[str, Any]] = Field(default_factory=list)
    latency_ms: Optional[float] = None
    skills_used: List[str] = Field(default_factory=list)
    corrections: List[str] = Field(default_factory=list)
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    notes: str = Field(default="")


class BrainResult(BaseModel):
    """The cognitive pipeline's answer for one BrainRequest."""

    model_config = ConfigDict(frozen=True)

    request_id: str
    response_text: str = Field(default="")
    artifacts: Dict[str, Any] = Field(default_factory=dict)
    plan: Optional[Plan] = None
    reflection: Optional[Reflection] = None
    handled: bool = Field(
        default=False,
        description="True once BrainCore actually processes requests "
        "(Phase 5.2+). Phase 5.1 pass-through sets False so callers "
        "know no cognition occurred.",
    )
